import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          'See': 'افضل تجرية لرؤية الاخبار\nحول العالم',
          'scince': 'علم',
          'health': 'الصحة',
          'sport': 'الرياضة',
          'Sport News': 'اخبار رياضية',
          'No news to show now': 'لا يوجد أخبار ليتم عرضها',
          'Loading......': '......انتظر',
          'All News': 'كل الأخبار',
          'Health News': 'أخبار الصحة',
          'Scince News': 'أخبار العلوم',
          'Dark Mode': 'النمط المظلم',
          'Change Language': 'تغيير اللغة',
          'Next': 'التالي',
          'See all news': 'رؤية كل الأخبار',
          'Help & Support': 'المساعدة والدعم',
          'Settings': 'الاعدادات',
          'Arabic Langauge': 'اللغة العربية',
          'English Langauge': 'اللغة الانجلزية',
          'Published At :': 'تاريخ النشر :',
          'Author :': 'الكاتب :',
          'Content :': 'المحتوى  :',
          'Desricption :': 'الوصف  :',
          'empty': 'فارغ',
          'You need internet to see news ':'انت بحاجة انترنت لاستخدام التطبيق',
          'You can see all type of news from drawer then all news ':'تستطيع رؤية جميع انواع الاخبار من القائمة الجانبية ثم كل الاخبار',
          'You can see the type of news you want from bottom bar ':'يمكنك رؤية نوع الخبر الذي تريده من خلال الشريط السفلي',
          'You can change theme or language from drawer then settings ':'تستطيع تغيير الوان ولغة التطبيق من القائمة الجانبية ثم الاعدادات',
          'FAQ :':'اسئلة شائعة :',
          'How to use this app':'كيفية استخدام هذاالتطبيق',
          'How made this app':'من صنع هذا التطبيق',
          'This app made by Mhamad Ibrahem':'لقد تمت صناعة هذا التطبيق بواسطة محمد ابراهيم',
        },

        // english translate

        'en': {
          'See': 'Best Experience To See News\nAround The Word',
          'scince': 'scince',
          'health': 'health',
          'sport': 'sport',
          'Sport News': 'Sport News',
          'No news to show now': 'No news to show now',
          'Loading......': 'Loading......',
          'All News': 'All News',
          'Health News': 'Health News',
          'Scince News': 'Science News',
          'Dark Mode': 'Dark Mode',
          'Change Language': 'Change Language',
          'Next': 'Next',
          'See all news': 'See all news',
          'Help & Support': 'Help & Support',
          'Settings': 'Settings',
          'Arabic Langauge': 'Arabic Langauge',
          'English Langauge': 'English Langauge',
          'Published At :': 'Published At :',
          'Content :': 'Content :',
          'Desricption :': 'Desricption :',
          'empty': 'empty',
          'You need internet to see news ':'You need internet to see news ',
          'You can see all type of news from drawer then all news ':'You can see all type of news from drawer then all news ',
          'You can see the type of news you want from bottom bar ':'You can see the type of news you want from bottom bar ',
          'You can change theme or language from drawer then settings ':'You can change theme or language from drawer then settings ',
          'FAQ :':'FAQ :',
          'How to use this app':'How to use this app',
          'How made this app':'How made this app',
          'This app made by Mhamad Ibrahem':'This app made by Mhamad Ibrahem',
        },
      };
}
